# -*- coding: utf-8 -*-
"""EDA on Bank-wise ATM, POS & Card Statistics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KqQpcL78R5NVIGRKsm-W4keWtMOGuc1h

***The rapid growth of digital banking and electronic payment systems has transformed the financial sector. Banks increasingly rely on ATMs, Point of Sale (POS) terminals, and debit/credit card services to improve customer convenience and transaction efficiency. However, variations in infrastructure deployment, transaction volume, and card usage across banks can significantly impact operational performance and customer accessibility.***

# **Problem Statement:**  

***This project aims to perform an Exploratory Data Analysis (EDA) on the dataset containing bank-wise ATM, POS, and card statistics from 2022 onwards. The analysis seeks to uncover trends, patterns, and relationships among different banking institutions regarding ATM installations, POS terminal distribution, debit/credit card issuance, and transaction activities.***
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/bankwise-atm-pos-card-statistics-2022-onwards.csv")
df.info()

"""# ***Data Inspection:***"""

df.shape

df.columns

df.dtypes

df.head()

"""- Identifying Columns:

 - Real Numerical Columns: atms_crms_onsite, atms_crms_offsite, pos, micro_atms, bharat_qr, upi_qr, credit_cards, debir_cards, cc_pay_trns_at_pos_vol, cc_pay_trns_at_pos_val, cc_pay_trns_online_vol, cc_pay_trns_online_val, cc_pay_trns_other_vol, cc_pay_trns_other_val, cc_cash_withdraw_atm_val,
 cc_cash_withdraw_atm_vol, dc_pay_trns_at_pos_vol, dc_pay_trns_at_pos_val, dc_pay_trns_online_vol, dc_pay_trns_online_val, dc_pay_trns_other_vol,dc_pay_trns_other_val, dc_cash_withdraw_atm_val,
 dc_cash_withdraw_atm_vol, dc_cash_withdraw_pos_val,
 dc_cash_withdraw_pos_vol.

 - Categorical columns: bank_category, bank_name
"""

df['bank_name'].value_counts()

df['bank_name'].nunique()

df['bank_category'].value_counts()

df['bank_category'].nunique()

df['date']=pd.to_datetime(df['date'])
df['date'].head()

df['month']=df['date'].dt.month
df['month'].head()

df['year']=df['date'].dt.year
df['year'].head()

"""# ***Statistical Summary:***"""

df.describe()

"""# ***DATA CLEANING:***

- Detecting Null Values.
"""

df.isnull().sum()

"""***- In financial datasets, preserving business meaning is more important than removing null values.***

- Finding Duplicates.
"""

df.duplicated().sum()

"""***- There are no duplicates in it data above.***

# ***Data Analysis:***

# ***Ranking Bank***
"""

a=df.groupby('bank_name')['atms_crms_onsite'].sum().sort_values(ascending=False).head(10)
a

plt.figure(figsize=(17,7))
sns.barplot(x=a.index,y=a,color='purple',legend=True)
plt.title("Frequency Distrubution of Banks and their ATM crms onsite.")
plt.show()

b=df.groupby('bank_name')['atms_crms_offsite'].sum().sort_values(ascending=False).head(10)
b

plt.figure(figsize=(17,7))
sns.barplot(x=b.index,y=b,color='purple',legend=True)
plt.title("Frequency Distrubution of Banks and their ATM crms offsite.")
plt.show()

"""- *State Bank of India recorded the highest ATM presence, indicating its dominance in physical banking infrastructure across India.*"""

d=df.groupby('bank_name')['micro_atms'].sum().sort_values(ascending=False).head(8)
d

plt.figure(figsize=(17,7))
sns.barplot(x=d.index,y=d,color='blue',legend=True)
plt.title("Frequency Distrubution of Banks and their Micro ATM's.")
plt.show()

"""- *Fino Payments Bank recorded the highest Micro_ATM presence, indicating its dominance in physical banking infrastructure across India.*"""

c=df.groupby("bank_name")['pos'].sum().sort_values(ascending=False).head(10)
c

plt.figure(figsize=(17,7))
sns.barplot(x=c.index,y=c,color='pink',legend=True)
plt.title("Frequency Distrubution of Banks and their POS machines.")
plt.show()

e=df.groupby('bank_name')['bharat_qr'].sum().sort_values(ascending=False).head(8)
e

plt.figure(figsize=(17,7))
sns.barplot(x=e.index,y=e,color='green',legend=True)
plt.title("Frequency Distrubution of Banks and their Bharat Qr's.")
plt.show()

"""- *Private sector banks such as HDFC Bank, ICICI Bank, Axis Bank and State Bank of India showed the highest POS and Bharat QR deployment, highlighting stronger digital payment expansion.*"""

f=df.groupby('bank_name')['upi_qr'].sum().sort_values(ascending=False).head(5)
f

plt.figure(figsize=(10,6))
sns.barplot(x=f.index,y=f,color='green',legend=True,estimator='sum')
plt.title("Frequency Distrubution of Banks and their UPI Qr's.")
plt.show()

"""- *Private sector banks such as Yes Bank and Axis Bank showed the highest UPI QR deployment, highlighting stronger digital payment expansion.*"""

pd.crosstab(df['bank_name'],df['bank_category'])

plt.figure(figsize=(10,20))
sns.scatterplot(x=df['bank_category'],y=df['bank_name'],color='red',legend=True)
plt.title("Frequency Distrubution of Banks and their Categories.")
plt.show()

"""- *Overall, the chart serves as a straightforward visual classification matrix that maps a sample of banks operating in India to their specific regulatory categories. It highlights that Private Sector and Foreign banks, Public Sector Banks make up the bulk of this specific dataset, Payment Banks are the least represented, and specialized institutions (like Small Finance and Payment Banks) almost always include their category directly in their naming convention.*"""

df.groupby('credit_cards')['debit_cards'].sum().sort_values(ascending=False).head(5)

plt.figure(figsize=(10,6))
sns.scatterplot(x=df['credit_cards'],y=df['debit_cards'],color='red',legend=True)
plt.title("Frequency Distrubution of Banks and their Categories.")
plt.show()

x=df.groupby('bank_name')['credit_cards'].sum().sort_values(ascending=False).head(5)
x

plt.figure(figsize=(10,6))
sns.barplot(x=x.index,y=x,color='blue',legend=True)
plt.title("Frequency Distrubution of Banks and their Categories.")
plt.show()

"""- *Overall, the data establishes a strictly descending hierarchy among these five major Indian banks, emphasizing **HDFC Bank's** dominant position at the top with a value exceeding 868 million, while revealing a substantial drop-off followed by **State Bank of India**,**ICICI Bank**,**Axis Bank**,**Kotak Mahindra Bank** for their Credit Cards during 2022-2025 .*"""

x=df.groupby('bank_name')['debit_cards'].sum().sort_values(ascending=False).head(5)
x

plt.figure(figsize=(10,6))
sns.barplot(x=x.index,y=x,color='blue',legend=True)
plt.title("Frequency Distrubution of Banks and their Categories.")
plt.show()

"""- *Overall, the data illustrates a massive disparity at the top, emphasizing **State Bank of India's** overwhelming dominance with a value exceeding 10.8 billion—roughly three times that of the second-place **Bank of Baroda**—while the remaining banks form a much tighter, lower-tier cluster in Credit Cards during 2022-2025.*"""

a=pd.pivot_table(df,index='bank_name',columns='year',values='credit_cards',aggfunc='sum',margins=True).sort_values(by='All',ascending=False).head(5)
a

plt.figure(figsize=(10,6))
sns.barplot(x=a.index,y=a['All'],color='purple')
plt.title("Total Credit Cards by Bank (All Years)")

y=pd.pivot_table(df,index='bank_name',columns='year',values='debit_cards',aggfunc='sum',margins=True).sort_values(by='All',ascending=False).head(5)
y

plt.figure(figsize=(10,6))
sns.barplot(x=y.index,y=y['All'],color='purple')
plt.title("Total Debit Cards by Bank (All Years)")

y=pd.pivot_table(df,index='bank_name',columns='year',values='debit_cards',aggfunc='sum',margins=True).sort_values(by='All',ascending=True).head(5)
y

plt.figure(figsize=(10,6))
sns.barplot(x=y.index,y=y['All'],color='purple')
plt.title("Total Debit Cards by Bank (All Years)")

df.groupby('year')["atms_crms_onsite"].sum()

plt.figure(figsize=(10,6))
sns.lineplot(x=df['year'],y=df['atms_crms_onsite'],color='blue',legend=True)
plt.title("Frequency Distrubution of ATM Crms Onsite Yearly.")
plt.show()

df.groupby('year')['atms_crms_offsite'].sum()

plt.figure(figsize=(10,6))
sns.lineplot(x=df['year'],y=df['atms_crms_offsite'],color='blue',legend=True)
plt.title("Frequency Distrubution of ATM crms off site Yearly.")
plt.show()

"""- *ATM transaction dependency is likely to reduce gradually as mobile banking and UPI adoption continue increasing.*
- *ATM transaction dependency showed slower growth compared to online banking channels, suggesting a gradual shift from cash-based transactions toward digital payments.*
"""

df.groupby("year")['pos'].sum()

plt.figure(figsize=(10,6))
sns.lineplot(x=df['year'],y=df['pos'],color='blue',legend=True)
plt.title("Frequency Distrubution of Pos Yearly.")
plt.show()

"""- *Overall, the data highlights a clear trajectory of rapid growth from 2022 that peaks at nearly 109.7 million in 2024, before experiencing a slight contraction in 2025.*"""

df.groupby('year')['micro_atms'].sum()

plt.figure(figsize=(10,6))
sns.lineplot(x=df['year'],y=df['micro_atms'],color='blue',legend=True)
plt.title("Frequency Distrubution of Micro Atms Yearly.")
plt.show()

"""- *The increasing number of micro ATMs suggests a growing reach of banking services in remote or underserved areas, contributing to financial inclusion.*"""

df.groupby('year')['debit_cards'].sum()

plt.figure(figsize=(10,6))
sns.lineplot(x=df['year'],y=df['debit_cards'],color='blue',legend=True)
plt.title("Frequency Distrubution of Debit Cards Yearly.")
plt.show()

"""- *Debit card online transaction volume shows a decrease in 2025 for State Bank of India and HDFC Bank, indicating a potential shift in consumer behavior or increased competition from other payment methods.*"""

df.groupby("year")['credit_cards'].sum()

plt.figure(figsize=(10,6))
sns.lineplot(x=df['year'],y=df['credit_cards'],color='blue',legend=True)
plt.title("Frequency Distrubution of Credit Cards Yearly.")
plt.show()

"""- *Credit card transaction values increased significantly by 2025, indicating growth in e-commerce spending and digital consumer behavior.*

# ***Credit vs Debit Transaction volume:***
"""

cc_pos_vol=df.groupby('bank_name')['cc_pay_trns_at_pos_vol'].sum().sort_values(ascending=False).head(5)
cc_pos_vol

plt.figure(figsize=(10,6))
sns.barplot(x=cc_pos_vol.index,y=cc_pos_vol,color='blue')
plt.title("Total Credit Cards by Bank (All Years)")

"""- *Overall, the data highlights HDFC Bank's clear market dominance with a volume exceeding 2.3 billion—nearly double that of its closest competitors—while Axis Bank and State Bank of India remain closely matched in the middle tier in Credit Card Pos Transaction.*"""

dc_pos_vol=df.groupby('bank_name')['dc_pay_trns_at_pos_vol'].sum().sort_values(ascending=False).head(5)
dc_pos_vol

plt.figure(figsize=(10,6))
sns.barplot(x=dc_pos_vol.index,y=dc_pos_vol,color='blue')
plt.title("Total Debit Cards by Bank (All Years)")

"""- *Overall, the data illustrates **State Bank of India's** commanding lead with a volume of nearly 1.77 billion—more than double that of second-place **HDFC Bank**—while the remaining banks trail significantly behind in Debit Card POS Transactions.*"""

cc_online_vol=df.groupby('bank_name')['cc_pay_trns_online_vol'].sum().sort_values(ascending=False).head(5)
cc_online_vol

plt.figure(figsize=(10,6))
sns.barplot(x=cc_online_vol.index,y=cc_online_vol,color='blue')
plt.title("Total Credit Cards by Bank (All Years)")

"""- *Overall, the data highlights **ICICI Bank's** leading position with a volume exceeding 1.82 billion, followed by a remarkably tight race for second place between **HDFC Bank** and **State Bank of India**, while **IndusInd Bank** trails significantly behind at the bottom in Credit Card Online Transactions.*"""

dc_online_vol=df.groupby('bank_name')['dc_pay_trns_online_vol'].sum().sort_values(ascending=False).head(5)
dc_online_vol

plt.figure(figsize=(10,6))
sns.barplot(x=dc_online_vol.index,y=dc_online_vol,color='blue')
plt.title("Total Debit Cards by Bank (All Years)")

"""- *Overall, the data demonstrates **State Bank of India's** clear lead with a volume exceeding 620 million, followed by a solid second-place showing from **HDFC Bank**, while the remaining three institutions trail significantly behind with **Union Bank of India** and **Axis Bank** locked in a close race at the bottom in Debit Card Online Transactions.*"""

cc_others_vol=df.groupby('bank_name')['cc_pay_trns_other_vol'].sum().sort_values(ascending=False).head(5)
cc_others_vol

plt.figure(figsize=(10,6))
sns.barplot(x=cc_others_vol.index,y=cc_others_vol,color='blue')
plt.title("Total Credit Cards by Bank (All Years)")

"""- *Overall, the data highlights an extreme anomaly where **Utkarsh Small Finance Bank** completely dominates with a volume exceeding 11.1 million, massively dwarfing the remaining banks in Credit Card Others Transactions which register practically negligible figures in comparison*"""

dc_others_vol=df.groupby('bank_name')['dc_pay_trns_other_vol'].sum().sort_values(ascending=False).head(5)
dc_others_vol

plt.figure(figsize=(10,6))
sns.barplot(x=dc_others_vol.index,y=dc_others_vol,color='blue')
plt.title("Total Debit Cards by Bank (All Years)")

"""- *Overall, the data reveals a massive lead by **HDFC Bank** with a volume near 7 million—more than ten times that of its closest competitor, **Axis Bank**—while the remaining banks tail off significantly toward the bottom in Debit Card Others Transactions.*"""

cc_atm_vol=df.groupby('bank_name')['cc_cash_withdraw_atm_vol'].sum().sort_values(ascending=False).head(5)
cc_atm_vol

plt.figure(figsize=(10,6))
sns.barplot(x=cc_atm_vol.index,y=cc_atm_vol,color='blue')
plt.title("Total Credit Cards by Bank (All Years)")

"""- *Overall, the data highlights **HDFC Bank's** massive lead with a credit card ATM cash withdrawal volume exceeding 50 million—more than double that of second-place **State Bank of India**—while the remaining banks show a steady decline down to **ICICI Bank**.*"""

dc_atm_vol=df.groupby('bank_name')['dc_cash_withdraw_atm_vol'].sum().sort_values(ascending=False).head(5)
dc_atm_vol

plt.figure(figsize=(10,6))
sns.barplot(x=dc_atm_vol.index,y=dc_atm_vol,color='blue')
plt.title("Total Debit Cards by Bank (All Years)")

"""- *Overall, the data demonstrates **State Bank of India's** overwhelming dominance with a debit card ATM cash withdrawal volume exceeding 38.1 billion—nearly four times that of second-place **HDFC Bank**—while the remaining public sector banks form a tightly packed lower tier.*"""

dc_cash_vol=df.groupby('bank_name')['dc_cash_withdraw_pos_vol'].sum().sort_values(ascending=False).head(5)
dc_cash_vol

plt.figure(figsize=(10,6))
sns.barplot(x=dc_cash_vol.index,y=dc_cash_vol,color='blue')
plt.title("Total Debit Cards by Bank (All Years)")

"""- *Overall, the data establishes a highly competitive landscape for debit card cash withdrawals at POS terminals, with **State Bank of India** holding a narrow lead over **HDFC Bank** at roughly 1.35 million versus 1.07 million, followed by a gradual decline down to **Union Bank of India** at the bottom.*

# ***Credit vs Debit Transaction Values:***
"""

cc_pos_val=df.groupby('bank_name')['cc_pay_trns_at_pos_val'].sum().sort_values(ascending=False).head(5)
cc_pos_val

plt.figure(figsize=(10,6))
sns.barplot(x=cc_pos_val.index,y=cc_pos_val,color='blue')
plt.title("Total Credit Cards by Bank (All Years)")

"""- *Overall, the data demonstrates HDFC Bank's distinct market leadership with a value exceeding 6.66 billion, followed by a relatively competitive middle tier led by State Bank of India, while RBL Bank trails significantly at the bottom with roughly 1.22 billion.*"""

dc_pos_val=df.groupby('bank_name')['dc_pay_trns_at_pos_val'].sum().sort_values(ascending=False).head(5)
dc_pos_val

plt.figure(figsize=(10,6))
sns.barplot(x=dc_pos_val.index,y=dc_pos_val,color='blue')
plt.title("Total Debit Cards by Bank (All Years)")

"""- *Overall, the data highlights State Bank of India's clear dominance with a transaction value of nearly 3.97 billion—roughly double that of second-place HDFC Bank—while the remaining banks show a steady decline down to Canara Bank at the bottom.*"""

cc_online_val=df.groupby('bank_name')['cc_pay_trns_online_val'].sum().sort_values(ascending=False).head(5)
cc_online_val

plt.figure(figsize=(10,6))
sns.barplot(x=cc_online_val.index,y=cc_online_val,color='blue')
plt.title("Total Credit Cards by Bank (All Years)")

"""- *Overall, the data establishes **HDFC Bank's** strong market leadership with an online credit card transaction value exceeding 11.49 billion, followed by a highly competitive middle tier featuring **ICICI Bank** and **State Bank of India**, while **IndusInd Bank** anchors the bottom of the list at roughly 2.2 billion.*"""

dc_online_val=df.groupby('bank_name')['dc_pay_trns_online_val'].sum().sort_values(ascending=False).head(5)
dc_online_val

plt.figure(figsize=(10,6))
sns.barplot(x=dc_online_val.index,y=dc_online_val,color='blue')
plt.title("Total Debit Cards by Bank (All Years)")

"""- *Overall, the data establishes **HDFC Bank** and **State Bank of India** as the market frontrunners with online debit card transaction values exceeding 1.62 billion and 1.36 billion respectively, followed by a steady, step-down decline through the remaining private banks.*"""

cc_other_val=df.groupby('bank_name')['cc_pay_trns_other_val'].sum().sort_values(ascending=False).head(5)
cc_other_val

plt.figure(figsize=(10,6))
sns.barplot(x=cc_other_val.index,y=cc_other_val,color='blue')
plt.title("Total Credit Cards by Bank (All Years)")

"""- *Overall, the data reveals a massive anomaly where Utkarsh Small Finance Bank completely dominates the category with a transaction value exceeding 2.12 million—nearly twenty times that of second-place ICICI Bank—while the remaining banks tail off to practically negligible amounts at the bottom.*"""

dc_other_val=df.groupby('bank_name')['dc_pay_trns_other_val'].sum().sort_values(ascending=False).head(5)
dc_other_val

plt.figure(figsize=(10,6))
sns.barplot(x=dc_other_val.index,y=dc_other_val,color='blue')
plt.title("Total Debit Cards by Bank (All Years)")

"""- *Overall, the data highlights **HDFC Bank's** overwhelming lead with a transaction value near 69.88 million—more than four times that of second-place **Axis Bank**—followed by a steep decline down to **Bank of Maharashtra** at the bottom.*"""

cc_atm_val=df.groupby('bank_name')['cc_cash_withdraw_atm_val'].sum().sort_values(ascending=False).head(5)
cc_atm_val

plt.figure(figsize=(10,6))
sns.barplot(x=cc_atm_val.index,y=cc_atm_val,color='blue')
plt.title("Total Credit Cards by Bank (All Years)")

"""- *Overall, the data demonstrates **HDFC Bank's** leading position with a credit card ATM cash withdrawal value exceeding 8.13 million, followed by a steady step-down decline through **State Bank of India** and the remaining top-tier banks.*"""

dc_atm_val=df.groupby('bank_name')['dc_cash_withdraw_atm_val'].sum().sort_values(ascending=False).head(5)
dc_atm_val

plt.figure(figsize=(10,6))
sns.barplot(x=dc_atm_val.index,y=dc_atm_val,color='blue')
plt.title("Total Debit Cards by Bank (All Years)")

"""- *Overall, the data demonstrates **State Bank of India's** overwhelming dominance with a debit card ATM cash withdrawal value exceeding 74.6 billion—nearly four times that of second-place **Union Bank of India**—while the remaining banks follow in a gradual, step-down decline.*"""

dc_atm_pos_val=df.groupby('bank_name')['dc_cash_withdraw_pos_val'].sum().sort_values(ascending=False).head(5)
dc_atm_pos_val

plt.figure(figsize=(10,6))
sns.barplot(x=dc_atm_pos_val.index,y=dc_atm_pos_val,color='blue')
plt.title("Total Debit Cards by Bank (All Years)")

"""- *Overall, the data establishes a highly competitive landscape for debit card cash withdrawals at POS terminals, with **State Bank of India** holding a clear lead at over 1.43 million, followed closely by **HDFC Bank** and **Indian Bank**, while **Union Bank of India** anchors the bottom of the group.*

# ***Credit vs Debit Analysis Volumes of year wise***
"""

cc_pos_vol_yearly = df.groupby(['bank_name', 'year','bank_category'])['cc_pay_trns_at_pos_vol'].sum().sort_values(ascending=False).head(15)
cc_pos_vol_yearly

cc_pos_vol_yearly_df = cc_pos_vol_yearly.reset_index()
plt.figure(figsize=(14, 7))
sns.barplot(x='bank_name', y='cc_pay_trns_at_pos_vol', hue='year', data=cc_pos_vol_yearly_df, palette='viridis')
plt.title("Top Banks by Credit Card POS Transaction Volume (Yearly)")
plt.xlabel("Bank Name")
plt.ylabel("Credit Card POS Transaction Volume")
plt.tight_layout()
plt.show()

"""- *Overall, the data highlights **HDFC Bank's** massive multi-year market leadership, peaking at over 767 million transactions in 2025, while showcasing a broader trend where private sector giants outpace **State Bank of India**, which experienced a steady post-2023 decline.*"""

dc_pos_vol_yearly = df.groupby(['bank_name', 'year','bank_category'])['dc_pay_trns_at_pos_vol'].sum().sort_values(ascending=False).head(15)
dc_pos_vol_yearly

dc_pos_vol_yearly_df = dc_pos_vol_yearly.reset_index()
plt.figure(figsize=(14, 7))
sns.barplot(x='bank_name', y='dc_pay_trns_at_pos_vol', hue='year', data=dc_pos_vol_yearly_df,palette='viridis')
plt.title("Top Banks by Debit Card POS Transaction Volume (Yearly)")
plt.xlabel("Bank Name")
plt.ylabel("Debit Card POS Transaction Volume")
plt.tight_layout()
plt.show()

"""- *Overall, the data demonstrates **State Bank of India's** multi-year dominance in the volume of debit card POS transactions despite suffering a massive, continuous year-on-year decline from 2022 to 2025, while the leading private sector banks similarly exhibit a general downward trajectory over the same period.*"""

cc_online_vol_yearly = df.groupby(['bank_name', 'year','bank_category'])['cc_pay_trns_online_vol'].sum().sort_values(ascending=False).head(15)
cc_online_vol_yearly

cc_online_vol_yearly_df = cc_online_vol_yearly.reset_index()
plt.figure(figsize=(14, 7))
sns.barplot(x='bank_name', y='cc_pay_trns_online_vol', hue='year', data=cc_online_vol_yearly_df, palette='viridis')
plt.title("Top Banks by Credit Card Online Transaction Volume (Yearly)")
plt.xlabel("Bank Name")
plt.ylabel("Credit Card Online Transaction Volume")
plt.tight_layout()
plt.show()

"""- *Overall, the data underscores **ICICI Bank's** impressive multi-year leadership in online credit card transaction volumes, maintaining the top spots in 2024 and 2025 at nearly 600 million transactions, while **State Bank of India** demonstrates strong public sector growth by surging ahead of **HDFC Bank** in the later years.*"""

dc_online_vol_yearly = df.groupby(['bank_name', 'year','bank_category'])['dc_pay_trns_online_vol'].sum().sort_values(ascending=False).head(15)
dc_online_vol_yearly

dc_online_vol_yearly_df = dc_online_vol_yearly.reset_index()
plt.figure(figsize=(14, 7))
sns.barplot(x='bank_name', y='dc_pay_trns_online_vol', hue='year', data=dc_online_vol_yearly_df, palette='viridis')
plt.title("Top Banks by Debit Card Online Transaction Volume (Yearly)")
plt.xlabel("Bank Name")
plt.ylabel("Debit Card Online Transaction Volume")
plt.tight_layout()
plt.show()

"""- *Overall, the data reveals a sharp, continuous multi-year decline in online debit card transaction volumes from 2022 to 2025 across all major institutions, while **State Bank of India** and **HDFC Bank** consistently maintain their positions as the top two market leaders throughout the contraction.*"""

cc_others_vol_yearly = df.groupby(['bank_name', 'year','bank_category'])['cc_pay_trns_other_vol'].sum().sort_values(ascending=False).head(5)
cc_others_vol_yearly

cc_others_vol_yearly_df = cc_others_vol_yearly.reset_index()
plt.figure(figsize=(14, 7))
sns.barplot(x='bank_name', y='cc_pay_trns_other_vol', hue='year', data=cc_others_vol_yearly_df, palette='viridis')
plt.title("Top Banks by Credit Card Online Transaction Volume (Yearly)")
plt.xlabel("Bank Name")
plt.ylabel("Credit Card Online Transaction Volume")
plt.tight_layout()
plt.show()

"""- *Overall, the data highlights an extraordinary surge by **Utkarsh Small Finance Bank**, which rocketed from around 609,000 transactions in 2024 to an overwhelming peak of over 10.5 million in 2025, completely eclipsing the relatively flat, lower-tier volumes recorded by **AU Small Finance Bank** over the multi-year period.*"""

dc_others_vol_yearly = df.groupby(['bank_name', 'year','bank_category'])['dc_pay_trns_other_vol'].sum().sort_values(ascending=False).head(8)
dc_others_vol_yearly

dc_others_vol_yearly_df = dc_others_vol_yearly.reset_index()
plt.figure(figsize=(14, 7))
sns.barplot(x='bank_name', y='dc_pay_trns_other_vol', hue='year', data=dc_others_vol_yearly_df, palette='viridis')
plt.title("Top Banks by Debit Card Online Transaction Volume (Yearly)")
plt.xlabel("Bank Name")
plt.ylabel("Debit Card Online Transaction Volume")
plt.tight_layout()
plt.show()

"""- *Overall, the data highlights **HDFC Bank's** overwhelming multi-year leadership despite suffering a sharp, continuous decline from over 4.47 million transactions in 2022 down to roughly 448,000 in 2025, while competing private sector banks like **ICICI Bank** and **Axis Bank** trail far behind in a significantly lower tier.*"""

cc_atm_vol_yearly = df.groupby(['bank_name', 'year','bank_category'])['cc_cash_withdraw_atm_val'].sum().sort_values(ascending=False).head(15)
cc_atm_vol_yearly

cc_atm_vol_yearly_df = cc_atm_vol_yearly.reset_index()
plt.figure(figsize=(14, 7))
sns.barplot(x='bank_name', y='cc_cash_withdraw_atm_val', hue='year', data=cc_atm_vol_yearly_df, palette='viridis')
plt.title("Top Banks by Credit Card Cash Withdrawal (Yearly)")
plt.xlabel("Bank Name")
plt.ylabel("Credit Card Online Transaction Volume")
plt.tight_layout()
plt.show()

"""- *Overall, the data underscores **HDFC Bank's** consistent multi-year market leadership in credit card ATM cash withdrawal values, peaking at nearly 2.48 million in 2024, while **State Bank of India** firmly secures the second spot within a broader trend where transaction values across top banks peaked in 2024 before dropping in 2025.*"""

dc_atm_vol_yearly = df.groupby(['bank_name', 'year','bank_category'])['dc_cash_withdraw_atm_val'].sum().sort_values(ascending=False).head(15)
dc_atm_vol_yearly

dc_atm_vol_yearly_df = dc_atm_vol_yearly.reset_index()
plt.figure(figsize=(14, 7))
sns.barplot(x='bank_name', y='dc_cash_withdraw_atm_val', hue='year', data=dc_atm_vol_yearly_df, palette='viridis')
plt.title("Top Banks by Debit Card Cash Withdrawal(Yearly)")
plt.xlabel("Bank Name")
plt.ylabel("Debit Card Online Transaction Volume")
plt.tight_layout()
plt.show()

"""- *Overall, the data demonstrates **State Bank of India's** overwhelming multi-year dominance in debit card ATM cash withdrawal values, peaking at over 2.21 billion in 2023, while trailing institutions like **Union Bank of India** and **HDFC Bank** form a significantly lower tier that follows a similar downward trajectory into 2025.*"""

dc_atm_pos_vol_yearly = df.groupby(['bank_name', 'year','bank_category'])['dc_cash_withdraw_pos_val'].sum().sort_values(ascending=False).head(15)
dc_atm_pos_vol_yearly

dc_atm_pos_vol_yearly_df = dc_atm_pos_vol_yearly.reset_index()
plt.figure(figsize=(14, 7))
sns.barplot(x='bank_name', y='dc_cash_withdraw_pos_val', hue='year', data=dc_atm_pos_vol_yearly_df, palette='viridis')
plt.title("Top Banks by Debit Card Cash Withdrawal at Pos Machines(Yearly)")
plt.xlabel("Bank Name")
plt.ylabel("Debit Card Online Transaction Volume")
plt.tight_layout()
plt.show()

"""- *Overall, the data shows **State Bank of India** holding the single highest annual value in 2022 at over 653,000, but **HDFC Bank** exhibits stronger multi-year resilience by peaking in 2023 at nearly 545,000, amid a broader trend where most major banks experienced a steady decline in debit card POS cash withdrawal values heading into 2025.*

# ***Debit vs Credit Transaction Values:***
"""

cc_pos_val_yearly = df.groupby(['bank_name', 'year','bank_category'])['cc_pay_trns_at_pos_val'].sum().sort_values(ascending=False).head(15)
cc_pos_val_yearly

cc_pos_val_yearly_df = cc_pos_val_yearly.reset_index()
plt.figure(figsize=(14, 7))
sns.barplot(x='bank_name', y='cc_pay_trns_at_pos_val', hue='year', data=cc_pos_val_yearly_df, palette='viridis')
plt.title("Top Banks by Credit Card POS Transaction Volume (Yearly)")
plt.xlabel("Bank Name")
plt.ylabel("Credit Card POS Transaction Volume")
plt.tight_layout()
plt.show()

"""- *Overall, the data highlights **HDFC Bank's** consistent multi-year dominance in credit card POS transaction values, peaking at nearly 2 billion in 2024, while a highly competitive secondary tier led by **State Bank of India** and **ICICI Bank** follows a similar broader trend of peaking in 2024 before dipping slightly in 2025.*"""

dc_pos_val_yearly = df.groupby(['bank_name', 'year','bank_category'])['dc_pay_trns_at_pos_val'].sum().sort_values(ascending=False).head(15)
dc_pos_val_yearly

dc_pos_val_yearly_df = dc_pos_val_yearly.reset_index()
plt.figure(figsize=(14, 7))
sns.barplot(x='bank_name', y='dc_pay_trns_at_pos_val', hue='year', data=dc_pos_val_yearly_df,palette='viridis')
plt.title("Top Banks by Debit Card POS Transaction Volume (Yearly)")
plt.xlabel("Bank Name")
plt.ylabel("Debit Card POS Transaction Volume")
plt.tight_layout()
plt.show()

"""- *Overall, the data highlights **HDFC Bank's** consistent multi-year dominance in credit card POS transaction values, peaking at nearly 2 billion in 2024, while a highly competitive secondary tier led by **State Bank of India** and **ICICI Bank** follows a similar broader trend of peaking in 2024 before dipping slightly in 2025.*"""

cc_online_val_yearly = df.groupby(['bank_name', 'year','bank_category'])['cc_pay_trns_online_val'].sum().sort_values(ascending=False).head(15)
cc_online_val_yearly

cc_online_val_yearly_df = cc_online_val_yearly.reset_index()
plt.figure(figsize=(14, 7))
sns.barplot(x='bank_name', y='cc_pay_trns_online_val', hue='year', data=cc_online_val_yearly_df, palette='viridis')
plt.title("Top Banks by Credit Card Online Transaction Volume (Yearly)")
plt.xlabel("Bank Name")
plt.ylabel("Credit Card Online Transaction Volume")
plt.tight_layout()
plt.show()

"""- *Overall, the data establishes **HDFC Bank's** continuous multi-year market leadership in online credit card transaction values, peaking at over 3.43 billion in 2024, followed by a highly competitive middle tier featuring **ICICI Bank** and **State Bank of India**, within a broader macro trend where transaction values across almost all top institutions peaked in 2024 before experiencing a slight contraction in 2025.*"""

dc_online_val_yearly = df.groupby(['bank_name', 'year','bank_category'])['dc_pay_trns_online_val'].sum().sort_values(ascending=False).head(15)
dc_online_val_yearly

dc_online_val_yearly_df = dc_online_val_yearly.reset_index()
plt.figure(figsize=(14, 7))
sns.barplot(x='bank_name', y='dc_pay_trns_online_val', hue='year', data=dc_online_val_yearly_df, palette='viridis')
plt.title("Top Banks by Debit Card Online Transaction Volume (Yearly)")
plt.xlabel("Bank Name")
plt.ylabel("Debit Card Online Transaction Volume")
plt.tight_layout()
plt.show()

"""- *Overall, the data positions **State Bank of India** and **HDFC Bank** as the dominant market leaders, with SBI securing the single highest annual value in 2022 at nearly 490 million before **HDFC Bank** took the lead from 2023 onward, within a broader macro trend where online debit card transaction values across all major banks faced a continuous decline into 2025.*"""

cc_other_val_yearly = df.groupby(['bank_name', 'year','bank_category'])['cc_pay_trns_other_val'].sum().sort_values(ascending=False).head(15)
cc_other_val_yearly

cc_other_val_yearly_df = cc_other_val_yearly.reset_index()
plt.figure(figsize=(14, 7))
sns.barplot(x='bank_name', y='cc_pay_trns_other_val', hue='year', data=cc_other_val_yearly_df, palette='viridis')
plt.title("Top Banks by Credit Card Online Transaction Volume (Yearly)")
plt.xlabel("Bank Name")
plt.ylabel("Credit Card Online Transaction Volume")
plt.tight_layout()
plt.show()

"""- *Overall, the data highlights an extraordinary surge by **Utkarsh Small Finance Bank**, which skyrocketed from approximately 101,000 in 2024 to an overwhelming peak of over 2.02 million in 2025, completely eclipsing the much lower-tier transaction values recorded by **ICICI Bank** and the remaining competitors across the multi-year period.*"""

dc_other_val_yearly_df = df.groupby(['bank_name', 'year','bank_category'])['dc_pay_trns_other_val'].sum().sort_values(ascending=False).head(15)
dc_other_val_yearly_df

dc_other_val_yearly_df = dc_other_val_yearly_df.reset_index()
plt.figure(figsize=(14, 7))
sns.barplot(x='bank_name', y='dc_pay_trns_other_val', hue='year', data=dc_other_val_yearly_df, palette='viridis')
plt.title("Top Banks by Debit Card Online Transaction Volume (Yearly)")
plt.xlabel("Bank Name")
plt.ylabel("Debit Card Online Transaction Volume")
plt.tight_layout()
plt.show()

"""- *Overall, the data demonstrates **HDFC Bank's** dominant multi-year market leadership despite experiencing a sharp, continuous decline from over 31.89 million in 2022 down to roughly 7.11 million in 2025, within a broader trend where transaction values across all competing banks—such as **Axis Bank** and **ICICI Bank**—similarly contracted over the same period.*"""

cc_atm_val_yearly_df = df.groupby(['bank_name', 'year','bank_category'])['cc_cash_withdraw_atm_val'].sum().sort_values(ascending=False).head(15)
cc_atm_val_yearly_df

cc_atm_val_yearly_df = cc_atm_val_yearly_df.reset_index()
plt.figure(figsize=(14, 7))
sns.barplot(x='bank_name', y='cc_cash_withdraw_atm_val', hue='year', data=cc_atm_val_yearly_df, palette='viridis')
plt.title("Top Banks by Credit Card Online Transaction Volume (Yearly)")
plt.xlabel("Bank Name")
plt.ylabel("Credit Card Online Transaction Volume")
plt.tight_layout()
plt.show()

"""- Overall, the data underscores **HDFC Bank's** consistent multi-year market leadership in credit card ATM cash withdrawal values, peaking at nearly 2.48 million in 2024, while **State Bank of India** firmly secures the second spot within a broader trend where transaction values across top banks peaked in 2024 before dropping in 2025."""

dc_atm_val_yearly_df = df.groupby(['bank_name', 'year','bank_category'])['dc_cash_withdraw_atm_val'].sum().sort_values(ascending=False).head(15)
dc_atm_val_yearly_df

dc_atm_val_yearly_df = dc_atm_val_yearly_df.reset_index()
plt.figure(figsize=(14, 7))
sns.barplot(x='bank_name', y='dc_cash_withdraw_atm_val', hue='year', data=dc_atm_val_yearly_df, palette='viridis')
plt.title("Top Banks by Debit Card Online Transaction Volume (Yearly)")
plt.xlabel("Bank Name")
plt.ylabel("Debit Card Online Transaction Volume")
plt.tight_layout()
plt.show()

"""- *Overall, the data demonstrates **State Bank of India's** overwhelming multi-year dominance in debit card ATM cash withdrawal values, peaking at over 2.21 billion in 2023, while trailing institutions like **Union Bank of India** and **HDFC Bank** form a significantly lower tier that follows a similar downward trajectory into 2025.*"""

dc_cash_pos_val_yearly_df = df.groupby(['bank_name', 'year','bank_category'])['dc_cash_withdraw_pos_val'].sum().sort_values(ascending=False).head(15)
dc_cash_pos_val_yearly_df

dc_cash_pos_val_yearly_df = dc_cash_pos_val_yearly_df.reset_index()
plt.figure(figsize=(14, 7))
sns.barplot(x='bank_name', y='dc_cash_withdraw_pos_val', hue='year', data=dc_cash_pos_val_yearly_df, palette='viridis')
plt.title("Top Banks by Debit Card Online Transaction Volume (Yearly)")
plt.xlabel("Bank Name")
plt.ylabel("Debit Card Online Transaction Volume")
plt.tight_layout()
plt.show()

"""- *Overall, the data shows **State Bank of India** holding the single highest annual value in 2022 at over 653,000, but **HDFC Bank** exhibits stronger multi-year resilience by peaking in 2023 at nearly 545,000, amid a broader trend where most major banks experienced a steady decline in debit card POS cash withdrawal values heading into 2025.*

# ***CO-RELATIONAL ANALYSIS***
"""

plt.figure(figsize=(10,6))
sns.heatmap(df[['atms_crms_onsite',
       'atms_crms_offsite', 'pos', 'micro_atms', 'bharat_qr', 'upi_qr',
       'credit_cards', 'debit_cards']].corr(),annot=True,cmap='coolwarm')
plt.show()

"""
* **The ATM & Debit Card Stronghold:** There is a near-perfect correlation between **debit cards** and both **onsite ATMs** (**0.94**) and **offsite ATMs** (**0.92**). This highlights that debit card ecosystems remain heavily synchronized with physical cash infrastructure.
* **The Credit Card & Merchant Nexus:** **Credit cards** show a massive correlation with **POS terminals** (**0.87**) and **Bharat QR** (**0.84**). This underscores their dominance in structured retail and merchant point-of-sale environments.
"""

plt.figure(figsize=(10,6))
sns.heatmap(df[['cc_pay_trns_at_pos_vol',
       'cc_pay_trns_at_pos_val', 'dc_pay_trns_at_pos_vol',
       'dc_pay_trns_at_pos_val']].corr(),annot=True,cmap='coolwarm')
plt.show()

"""* **Intra-Card Volume and Value Synchronicity:** Both credit cards and debit cards show a near-perfect internal correlation between their transaction volumes and transaction values. Debit cards lead with an exceptionally tight correlation of **0.98**, closely followed by credit cards at **0.96**. This confirms that as transaction counts grow within either category, total spend scales almost perfectly linearly.
* **The High-Value Cross-Connection:** There is a strong cross-correlation (**0.73**) between credit card transaction values (`cc_pay_trns_at_pos_val`) and debit card transaction values (`dc_pay_trns_at_pos_val`). This suggests that broader macroeconomic factors driving point-of-sale spending levels tend to elevate overall spending across both card types simultaneously.

"""

plt.figure(figsize=(10,6))
sns.heatmap(df[['cc_pay_trns_online_vol',
       'cc_pay_trns_online_val', 'dc_pay_trns_online_vol',
       'dc_pay_trns_online_val']].corr(),annot=True,cmap='coolwarm')
plt.show()

"""* **High Internal Synchronicity:** Both card types exhibit a very strong internal alignment between transaction volume and total transaction value. Credit cards show a tightly coupled correlation of **0.93**, while debit cards follow closely behind at **0.91**. This indicates that a rise in transaction frequency within either category maps reliably to a proportional increase in total spending online.
* **The Interconnected Value Trend:** There is a remarkably strong cross-correlation (**0.88**) between credit card transaction values (`cc_pay_trns_online_val`) and debit card transaction values (`dc_pay_trns_online_val`). This suggests that digital commerce spending spikes—likely driven by seasonal e-commerce sales or macro economic trends—tend to lift total monetary value across both payment instruments simultaneously.

"""

plt.figure(figsize=(10,6))
sns.heatmap(df[['cc_pay_trns_other_vol',
       'cc_pay_trns_other_val', 'dc_pay_trns_other_vol',
       'dc_pay_trns_other_val']].corr(),annot=True,cmap='coolwarm')
plt.show()

"""* **Absolute Credit Card Volume and Value Alignment:** Credit card transactions in the "other" category exhibit a near-perfect internal correlation of **0.99** between volume (`cc_pay_trns_other_vol`) and value (`cc_pay_trns_other_val`). This demonstrates an incredibly tight linear relationship, where any fluctuation in transaction frequency maps almost perfectly to the total transaction value.
* **Robust Debit Card Synchronicity:** Similarly, debit card "other" transactions show a highly robust internal correlation of **0.93** between volume and value. This confirms that transaction frequency remains a highly dependable indicator of overall monetary spend within the debit ecosystem as well.
* **Complete Cross-Card Independence:** The most striking feature of the matrix is the absolute disconnect between credit and debit card metrics, with cross-correlations hovering near zero (ranging from **-0.0056** to **-0.0099**). This complete independence indicates that the market forces, use cases, or consumer habits driving "other" payment transactions on credit cards operate entirely separate from those on debit cards.
"""

plt.figure(figsize=(10,6))
sns.heatmap(df[['cc_cash_withdraw_atm_vol',
       'cc_cash_withdraw_atm_val', 'dc_cash_withdraw_atm_vol',
       'dc_cash_withdraw_atm_val','dc_cash_withdraw_pos_val',
       'dc_cash_withdraw_pos_vol']].corr(),annot=True,cmap='coolwarm')
plt.show()

"""* **Near-Perfect Internal Channel Alignment:** Every cash withdrawal method demonstrates a near-perfect internal correlation between transaction volume and total monetary value. Debit card ATM withdrawals lead with an incredibly tight alignment of **0.99**, while both credit card ATM withdrawals (**0.98**) and debit card POS cash withdrawals (**0.98**) follow right behind. Within each channel, transaction frequency dictates total cash value almost perfectly.
* **Shared ATM Demand Drivers:** There is a moderate-to-strong cross-correlation between credit card and debit card ATM cash withdrawal values (**0.62**). This implies that broader systemic or macroeconomic factors influencing a consumer's need to pull physical cash from an ATM impact both credit and debit users in a similar direction.
* **Distinct POS Cash Habits:** Debit card cash withdrawals at the Point of Sale (POS) have the weakest relationship with traditional credit card ATM usage (ranging between **0.41** and **0.46**). This lower correlation indicates that the behavioral habit of requesting cash back at a merchant counter operates on distinct consumer motivations compared to visiting an ATM.

# ***Anomaly Detection***
"""

sns.boxplot(df['pos'])
plt.title("Distribution of POS Usage")
plt.show()

sns.boxplot(df['atms_crms_offsite'])
plt.title("Distribution of ATM Usage")
plt.show()

sns.boxplot(df['atms_crms_onsite'])
plt.title("Distribution of ATM Usage")
plt.show()

sns.boxplot(df['micro_atms'])
plt.title("Distribution of Micro ATM Usage")
plt.show()

sns.boxplot(df['bharat_qr'])
plt.title("Distribution of QR Usage")
plt.show()

sns.boxplot(df['upi_qr'])
plt.title("Distribution of QR Usage")
plt.show()

sns.boxplot(df['credit_cards'])
plt.title("Distribution of Credit Card Usage")
plt.show()

sns.boxplot(df['debit_cards'])
plt.title("Distribution of Debit Card Usage")
plt.show()

"""# **Analysis Notes on Bank Statistics**

# ***Business Insights :***

1. The dataset contains analysis of 67 banks and 2671 records, showing a large-scale overview of India’s banking and digital payment ecosystem.
2. State Bank of India recorded the highest ATM presence, indicating its dominance in physical banking infrastructure across India.
3. Private sector banks such as HDFC Bank, ICICI Bank, and Axis Bank showed the highest POS and QR deployment, highlighting stronger digital payment expansion.
4. The analysis shows a significant increase in online debit and credit card transactions from 2022 to 2025, indicating rapid customer migration toward digital banking channels.
5. Debit card transactions contributed the highest transaction volume compared to credit cards, reflecting mass adoption among retail banking customers.
6. Credit card transactions showed higher average transaction values, especially in online commerce and POS-based spending.
7. Payment banks such as India Post Payments Bank and Fino Payments Bank recorded strong Micro ATM activity, supporting rural financial inclusion.
8. QR-based payment infrastructure expanded rapidly, with Bharat QR and UPI QR deployment increasing across major banks, reflecting India’s growing cashless economy.

# ***Trend Forecasting :***

***Based on the observed trends in the dataset:***

1. Based on the rising transaction trends between 2022 and 2025, digital transactions are expected to continue growing at a high rate in future years.
2. POS terminal deployment is expected to rise further as private banks continue merchant expansion programs.
3. QR-based transactions may eventually surpass traditional card-based small-value payments because of lower operational costs and faster processing.
4. ATM transaction dependency is likely to reduce gradually as mobile banking and UPI adoption continue increasing.
5. Online credit card transactions are expected to grow faster than offline transactions due to increasing e-commerce penetration.
6. Micro ATM adoption is likely to increase further in rural regions due to government-backed financial inclusion initiatives.

# ***Customer Segmentation :***

1. Traditional Banking Customers
- High ATM withdrawal usage
- Primarily debit card users
- More associated with public sector banks
2. Digital Banking Customers
- High online transaction frequency
- Frequent QR and POS usage
- Mainly associated with private sector banks
3. Rural Banking Customers
- Use Micro ATM services
- Depend on payment banks and rural banking networks
4. Premium Digital Customers
- Higher credit card spending
- More online and POS-based transactions
- Urban and e-commerce-oriented customers

# ***Year-wise Growth Percentage Insights :***

1. From 2022 to 2025, there is continuous growth in:
- Online transactions
- POS terminal deployment
- QR-based payment systems
- Debit and credit card usage
2. Digital payment infrastructure expanded significantly across major banks between 2022 and 2025, indicating rapid digital transformation in the Indian banking sector.
3. QR-based payment systems such as Bharat QR and UPI QR showed strong year-over-year growth, reflecting increasing customer preference for contactless transactions.
4. POS machine installations increased steadily from 2022 to 2025, especially among private sector banks like HDFC Bank, ICICI Bank, and Axis Bank.
5. Debit card transactions remained consistently higher in transaction volume throughout the years, showing widespread usage among retail banking customers.
6. Credit card transaction values increased significantly by 2025, indicating growth in e-commerce spending and digital consumer behavior.
7. ATM transaction dependency showed slower growth compared to online banking channels, suggesting a gradual shift from cash-based transactions toward digital payments.
8. Micro ATM deployment and payment bank activity expanded between 2022 and 2025, improving financial inclusion in rural and semi-urban areas.
9. Banks investing more heavily in digital infrastructure consistently recorded higher transaction activity and customer engagement over the years.
10. The overall trend from 2022–2025 clearly indicates India’s transition toward a more digital, cash-lite banking ecosystem driven by:
- Mobile banking
- QR payments
- POS expansion
- Online card transactions
- Fintech integration

# ***Predictive Insights :***

1. Digital transaction growth is expected to continue increasing beyond 2025 due to rising UPI and mobile banking adoption.
2. QR-based payments are likely to dominate low-value retail transactions in the future.
3. ATM growth may stabilize as customers increasingly rely on digital payment platforms.
4. Private sector banks are expected to continue leading digital payment innovation and merchant payment infrastructure.
5. Rural banking digitization is expected to grow further through Micro ATMs, payment banks, and government-supported financial inclusion programs.

# ***Recommendations for Banks :***

1. Banks should increase investment in digital payment infrastructure such as POS terminals, QR systems, and mobile banking platforms because digital transactions showed continuous growth from 2022–2025.
2. Public sector banks should improve digital banking services and online customer experience to compete effectively with private sector banks leading in digital payments.
3. Banks should expand Micro ATM services and rural digital banking networks to improve financial inclusion and banking accessibility in underserved regions.
4. Strong cybersecurity systems and fraud prevention mechanisms should be implemented due to the rapid increase in online and card-based transactions.
5. Banks should encourage merchants and customers to adopt cashless payment methods through incentives, awareness programs, and simplified digital onboarding.

# ***Recommendations for Policy Makers :***

1. Policy makers should continue promoting digital payment adoption through financial literacy and awareness programs across urban and rural regions.
2. Government should support the expansion of rural digital infrastructure, including internet connectivity, Micro ATMs, and digital banking facilities.
3. Strong regulatory frameworks for cybersecurity and customer data protection should be strengthened as digital banking usage increases.
4. Incentives and subsidies should be provided to small businesses and merchants for adopting POS machines and QR-based payment systems.
5. Policy makers should encourage collaboration between banks and fintech companies to accelerate innovation, improve digital accessibility, and strengthen India’s cashless economy.
"""